### ISSUE TITLE
🧹 Lint and format Kotlin source in Android SDK

### ISSUE THREAD

**Issue by phatblat** [phatblat/dotfiles#10]
# Problem

The Android SDK has a lot of Kotlin source files that are not formatted according
to the [Kotlin style guide](https://developer.android.com/kotlin/style-guide).
Developers formatting these files manually allows for inconsistencies and harder
to read code.

# Solution

We should evaulate the tools available and employ them in scripts so they are
easy to run and maintain. Linting should be added to the CI pipeline to ensure
that all code is formatted correctly. Developers will run the scripts to format
their code before committing.

https://github.com/getditto/ditto/pull/7161/files#diff-5fbb24cadfeb89eb30464269165000983267e43f35b1af40c7622a73e525e74eR219

### [Android lint](https://developer.android.com/studio/write/lint)

- Built into the Android Gradle Plugin: gradlew lint
- Configurable rule sets
- Supports 'baseline' files to ignore findings in code with `@SuppressLint`
  annotation
- Evaluates XML layouts and the android manifest
- Doesn't evaluate Kotlin code style

### [detekt](https://detekt.dev/)

- Static code analysis for Kotlin
- Gradle plugin
- Configurable rule sets `lint.xml`
- Ignore findings in code with `@Suppress` annotation

### [ktlint](https://pinterest.github.io/ktlint/)

- Style guide enforcement for Kotlin
- Configurable rule sets
- Built-in formatter

### [ktfmt](https://facebook.github.io/ktfmt/)

- formats Kotlin code according to the official Kotlin style guide
- not configurable in order to enforce consistency

## TODO

- [ ] Evaluate tools
- [ ] Create `scripts/android/lint.sh` script, include in `lint_all.sh`
- [ ] Create `scripts/android/format.sh` script, include in `format_all.sh`
- [ ] Add `lint-android` target to `Makefile`, include in `lint` target
- [ ] Add `format-android` target to `Makefile`, include in `format` target
- [ ] Add `lint-android` to CI pipeline

# Commentary

**Comment by phatblat** [comment]
wrong repo
